platform: rest
method: GET
resource: !secret url_sensor_luxtronik25_value
name: Luxtronik 25 Value State
unique_id: rest.sensor_luxtronik_25_value_state
value_template: "{% if state_attr('sensor.luxtronik_25_value_state', 'values')|safe == 'None' -%}NOK{%- else -%}OK{%- endif %}"
scan_interval: 60
force_update: true
json_attributes:
  - "values"